### ISSUE TITLE
 Compilation failure bootstrap class path not set in conjunction with -source 1.7

### ISSUE THREAD

**Issue by emmanuelbernard** [jcgay/homebrew-jcgay#1]
I am having the following problem in one of my projects.
Vanilla mvn works, but not maven-deluxe

```
$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

$ mvn clean install -D skipTests
[...]
Reactor Summary:

Hibernate OGM Bill of Materials .................... SUCCESS [  0.094 s]
Hibernate OGM Aggregator ........................... SUCCESS [  0.881 s]
Hibernate Object Grid Mapper Core .................. FAILURE [  2.003 s]
Hibernate OGM for Ehcache .......................... SKIPPED
Hibernate OGM for Infinispan ....................... SKIPPED
Hibernate OGM for MongoDB .......................... SKIPPED
Hibernate OGM for Neo4j ............................ SKIPPED
Hibernate OGM for CouchDB .......................... SKIPPED
Hibernate OGM for Cassandra ........................ SKIPPED
Hibernate OGM for Redis ............................ SKIPPED
Hibernate OGM JBoss Modules ........................ SKIPPED
Hibernate OGM WildFly Module ....................... SKIPPED
Hibernate Object Grid Mapper Performance tests ..... SKIPPED
Hibernate OGM Integration and performance Tests .... SKIPPED
Hibernate OGM Integration Test case ................ SKIPPED
Hibernate OGM Integration Tests for MongoDB ........ SKIPPED
Hibernate OGM Integration Tests for CouchDB ........ SKIPPED
Hibernate OGM Integration Tests for Neo4j .......... SKIPPED
Hibernate OGM Integration Tests for Redis .......... SKIPPED
Hibernate OGM Manual ............................... SKIPPED
Hibernate OGM Documentation ........................ SKIPPED
Hibernate OGM Examples ............................. SKIPPED
Hibernate OGM Getting Started ...................... SKIPPED
Hibernate OGM Javadoc .............................. SKIPPED
Hibernate OGM Distribution ......................... SKIPPED
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 3.923 s
Finished at: 2015-09-19T09:04:19+02:00
Final Memory: 36M/434M
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project hibernate-ogm-core: Compilation failure
bootstrap class path not set in conjunction with -source 1.7
-> [Help 1]
org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
bootstrap class path not set in conjunction with -source 1.7

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:915) ~[na:na]
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129) ~[na:na]
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) ~[maven-core-3.3.3.jar:3.3.3]
        ... 20 common frames omitted
Wrapped by: org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project hibernate-ogm-core: Compilation failure
bootstrap class path not set in conjunction with -source 1.7

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862) [maven-embedder-3.3.3.jar:3.3.3]
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286) [maven-embedder-3.3.3.jar:3.3.3]
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197) [maven-embedder-3.3.3.jar:3.3.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:na]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project hibernate-ogm-core: Compilation failure
bootstrap class path not set in conjunction with -source 1.7

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862) [maven-embedder-3.3.3.jar:3.3.3]
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286) [maven-embedder-3.3.3.jar:3.3.3]
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197) [maven-embedder-3.3.3.jar:3.3.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:na]
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
bootstrap class path not set in conjunction with -source 1.7

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:915) ~[na:na]
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129) ~[na:na]
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) ~[maven-core-3.3.3.jar:3.3.3]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) ~[maven-core-3.3.3.jar:3.3.3]
        ... 20 common frames omitted

Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

After correcting the problems, you can resume the build with the command
  mvn <goals> -rf :hibernate-ogm-core
```

Any clue?
We need Java 8 to build but force the source to 7 for backward compatibility.
I suspect it has to do with the extra JVM forking maven-deluxe does.

**Comment by jcgay** [comment]
Huuuuuum this is weird.

I have give it a try, and it works on my machine™ :(

```
$ mvn -version                                                                                                                                                                                      
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-06-13T11:24:28+02:00)
Maven home: /usr/local/Cellar/maven-deluxe/3.3.3-4/libexec
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"

$ java -version                                                                                                                                                                                     
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

$ mvn clean install -DskipTests -s settings-example.xml
[...]
------------------------------------------------------------------------
Reactor Summary:

Hibernate OGM Bill of Materials .................... SUCCESS [  0.124 s]
Hibernate OGM Aggregator ........................... SUCCESS [  0.742 s]
Hibernate Object Grid Mapper Core .................. SUCCESS [  7.740 s]
Hibernate OGM for Ehcache .......................... SUCCESS [  1.376 s]
Hibernate OGM for Infinispan ....................... SUCCESS [  1.543 s]
Hibernate OGM for MongoDB .......................... SUCCESS [  3.644 s]
Hibernate OGM for Neo4j ............................ SUCCESS [  2.649 s]
Hibernate OGM for CouchDB .......................... SUCCESS [  1.572 s]
Hibernate OGM for Cassandra ........................ SUCCESS [  1.267 s]
Hibernate OGM for Redis ............................ SUCCESS [  1.310 s]
Hibernate OGM JBoss Modules ........................ SUCCESS [  0.193 s]
Hibernate OGM WildFly Module ....................... SUCCESS [  2.779 s]
Hibernate Object Grid Mapper Performance tests ..... SUCCESS [  1.405 s]
Hibernate OGM Integration and performance Tests .... SUCCESS [  3.141 s]
Hibernate OGM Integration Test case ................ SUCCESS [  2.915 s]
Hibernate OGM Integration Tests for MongoDB ........ SUCCESS [  3.936 s]
Hibernate OGM Integration Tests for CouchDB ........ SUCCESS [  2.963 s]
Hibernate OGM Integration Tests for Neo4j .......... SUCCESS [  2.729 s]
Hibernate OGM Integration Tests for Redis .......... SUCCESS [  2.874 s]
Hibernate OGM Manual ............................... SUCCESS [ 17.011 s]
Hibernate OGM Documentation ........................ SUCCESS [  0.166 s]
Hibernate OGM Examples ............................. SUCCESS [  0.160 s]
Hibernate OGM Getting Started ...................... SUCCESS [  0.692 s]
Hibernate OGM Javadoc .............................. SUCCESS [01:12 min]
Hibernate OGM Distribution ......................... SUCCESS [ 12.458 s]
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 02:28 min
Finished at: 2015-09-19T15:24:53+02:00
Final Memory: 380M/1475M
------------------------------------------------------------------------
```

What I don't understand is that the error message you have is usually a warning message, are you sure to not have other error logged for the failing module ?

maven-deluxe does not fork a JVM, it can fails because of classloader issues with SLF4J (in fact Plexus ClassRealm isolation) but I don't encounter problems at the the time with my Java 8 project.

**Comment by emmanuelbernard** [comment]
Damn, now it works here too :(
No idea how and why it failed before, it's even the same shell instance.

Sorry about that noise.
